[project]
name = "ai-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch",
    "torchvision",
    "numpy",
    "matplotlib>=3.7.0",
]

[[tool.uv.sources]]
package = "torch"
index = "https://mirrors.aliyun.com/pytorch-wheels/cu128"

[[tool.uv.sources]]
package = "torchvision"
index = "https://mirrors.aliyun.com/pytorch-wheels/cu128"